### ISSUE TITLE
excuteOrder error

### ISSUE THREAD

**Issue by qinxi1122** [syp25815/bpx-api-py#2]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\dex\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda3\envs\dex\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\dex\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\dex\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/QuantProject/bpx-api-py-main/example/bpx_test.py", line 18, in <module>
    print(bpx.ExeOrder('SOL_USDC', 'Bid', 'Limit', 'IOC', '0.1', '116.35'))
  File "E:\QuantProject\bpx-api-py-main\bpx\bpx.py", line 74, in ExeOrder
    headers=self.sign('orderExecute', params)).json()
  File "D:\Anaconda3\envs\dex\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by syp25815** [comment]
解码错误属于交易所接口卡死导致，等他们平台流畅吧

**Comment by qinxi1122** [comment]
那就只能手动刷量了啊，磨损太大

**Comment by syp25815** [comment]
不用，我自己用Go的交易，千1，python刷东西本来就喜欢卡或者乱七八糟的错误，习惯就好

**Comment by qinxi1122** [comment]
大佬可以加个微信求脚本吗

**Comment by qinxi1122** [comment]
请问这是用的python本版本的问题吗，我是3.7

**Comment by syp25815** [comment]
> 请问这是用的python本版本的问题吗，我是3.7

是的，本地运行图

<img width="1131" alt="图片" src="https://github.com/syp25815/bpx-api-py/assets/160144860/46cb42f4-fab9-4b39-9cd5-7242bf77ecde">

**Comment by qinxi1122** [comment]
啊原来如此，请问需要多少版本？

**Comment by qinxi1122** [comment]
我前面余额也没问题，就是最后下单出错

**Comment by ZZzzzioi** [comment]
老哥这不给官方提交一下混个奖励嘛

**Comment by qinxi1122** [comment]
![my-pnl-on-kwenta](https://github.com/syp25815/bpx-api-py/assets/15192895/e9fe812c-b8e7-4369-8ad7-7957b7ece2bf)
大佬，是最后下单有问题

**Comment by qinxi1122** [comment]
帮忙看看吧

**Comment by optimus-a1** [comment]
大佬能写个网格交易的吗

**Comment by qinxi1122** [comment]
现在是交易有问题，发送不了订单，还提什么网格啊

**Comment by yexueyh** [comment]
是签名错误，不是网站问题

**Comment by qinxi1122** [comment]
> 是签名错误，不是网站问题

大佬，怎么解决呢

**Comment by qinxi1122** [comment]
> 是签名错误，不是网站问题

你的代码很安全，其他的看不懂的不敢用，能优化一下吗，我想跑起来！给你加星

**Comment by yexueyh** [comment]
> > 是签名错误，不是网站问题
> 
> 你的代码很安全，其他的看不懂的不敢用，能优化一下吗，我想跑起来！给你加星

直接从网页上扣

**Comment by syp25815** [comment]
来bp中文群，我在里面呢，然后我们tg私聊

**Comment by qinxi1122** [comment]
老哥，你的代码里有api，赶紧删掉

**Comment by meyafex** [comment]
After the last pull request changes, a JSONDecodeError will never appear again.
This issue can be closed.

**Comment by syp25815** [comment]
> After the last pull request changes, a JSONDecodeError will never appear again. This issue can be closed.

how to dm u tg? i will try.

**Comment by meyafex** [comment]
@syp25815 
> how to dm u tg? i will try.

If you mean telegram:  [@sndmnds](https://t.me/sndmnds)
