### ISSUE TITLE
Market 市价单如何调用？

### ISSUE THREAD

**Issue by ZZzzzioi** [syp25815/bpx-api-py#3]
示例里面给了限价单的执行调用，市价单里面不需要price这个参数，这时候该怎么调用呢？

重新写了个市价单的实例，如下：
```
def ExeOrderMarket(self, symbol, side, orderType, quantity):
    params = {
        'symbol': symbol,
        'side': side,
        'orderType': orderType,
        'quantity': quantity
    }
    return requests.post(url=f'{self.url}api/v1/order', proxies=self.proxies, data=json.dumps(params),
                         headers=self.sign('orderExecute', params)).json()
```
删掉了不必要的参数，但是调用还是会报错，麻烦老哥看下

**Comment by qinxi1122** [comment]
不是市价出错，我用限价单也是报错
![Uploading my-pnl-on-kwenta.png…]()

**Comment by qinxi1122** [comment]
大佬能不能给看看啊

**Comment by ZZzzzioi** [comment]
@qinxi1122 限价单我这边是没问题的，你的图加载不出来

**Comment by qinxi1122** [comment]
![my-pnl-on-kwenta](https://github.com/syp25815/bpx-api-py/assets/15192895/44f634e5-f66e-4391-a6ec-0151df892a8e)
你运行这个没问题吗

**Comment by ZZzzzioi** [comment]
> ![my-pnl-on-kwenta](https://private-user-images.githubusercontent.com/15192895/305624168-44f634e5-f66e-4391-a6ec-0151df892a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTg1ODIsIm5iZiI6MTcwODE1ODI4MiwicGF0aCI6Ii8xNTE5Mjg5NS8zMDU2MjQxNjgtNDRmNjM0ZTUtZjY2ZS00MzkxLWE2ZWMtMDE1MWRmODkyYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA4MjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTQ3YmFmMTQxOTBkNTdjMDkzNTMwODc5MjZiYTk1ODNkMmEyODk2MDNjYTllMWYwMDhiNGM0YTVjMWIyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IInp-cjIy3ULdwVN73sWeXyo62BinS8f6soMi63-aCE) 你运行这个没问题吗

我在本地跑的，没问题
<img width="503" alt="image" src="https://github.com/syp25815/bpx-api-py/assets/100181825/3ef7632d-5be7-498b-8460-8ad036b0ba40">

**Comment by qinxi1122** [comment]
你用的python啥版本
能加个微信吗

**Comment by ZZzzzioi** [comment]
> 你用的python啥版本 能加个微信吗

我加你吧

**Comment by ZZzzzioi** [comment]
目前官方不支持市价单的API接口
